<?php

namespace Aabadawy\RowCatcher\Test;
use Aabadawy\RowCatcher\RowCatcherServiceProvider;
use Orchestra\Testbench\TestCase as OrchestraTestCase;

class TestCase extends OrchestraTestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app)
    {
        return [
             RowCatcherServiceProvider::class,
        ];
    }
}